In [1]:
a=[1,2,3,4]
b=[2,3,4,5]

In [2]:
ab=[]
for i in range(0,len(a)):
    ab.append(a[i]*b[i])
ab

[2, 6, 12, 20]

In [3]:
import numpy as np

In [4]:
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
a*b

array([ 2,  6, 12, 20])

In [5]:
#Create a numpy array

In [6]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [7]:
a=np.array([1,2,3,4])

In [8]:
type(a)

numpy.ndarray

In [9]:
np.array([3.14,4,2,13])

array([ 3.14,  4.  ,  2.  , 13.  ])

In [14]:
np.array([3.14,4,2,13],dtype="float32")

array([ 3.14,  4.  ,  2.  , 13.  ], dtype=float32)

In [15]:
np.array([3.14,4,2,13],dtype="int")

array([ 3,  4,  2, 13])

In [16]:
np.array(a)

array([1, 2, 3, 4])

In [17]:
# types of the creating array

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros(5,dtype="int")

array([0, 0, 0, 0, 0])

In [21]:
np.ones((4,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [23]:
np.arange(1,31,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [25]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [27]:
np.random.normal(10,4,(3,4))

array([[17.10182297,  2.97070626, 14.04303646,  5.81264022],
       [ 9.18111681,  6.67637881,  9.08372333,  8.58558219],
       [ 5.40131999, 10.7702778 ,  8.55295321, 15.08054345]])

In [34]:
np.random.randn(2,4)

array([[-0.8158544 , -0.18495466,  1.33600989,  0.52234884],
       [-2.30965946, -0.34212457, -0.27180253,  0.85942682]])

In [35]:
np.random.randint(0,10,(3,3))

array([[7, 2, 3],
       [2, 5, 0],
       [5, 5, 8]])

In [36]:
#Attribute of the arrays

In [38]:
np.random.randint(5,size=10)

array([0, 4, 1, 2, 1, 2, 1, 2, 4, 4])

In [39]:
a=np.random.randint(5,size=10)

In [40]:
a.ndim

1

In [41]:
a.shape

(10,)

In [45]:
a.size

10

In [42]:
a.dtype

dtype('int32')

In [43]:
b=np.random.randint(10,size=(3,5))

In [44]:
b.ndim

2

In [46]:
b.shape

(3, 5)

In [47]:
b.size

15

In [48]:
b.dtype

dtype('int32')

In [49]:
#Array reshaping

In [52]:
c=np.arange(1,10)

In [53]:
c.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
d=np.random.randint(1,10,size=(3,5))
d

array([[8, 9, 2, 2, 8],
       [9, 9, 6, 4, 8],
       [1, 2, 6, 7, 5]])

In [57]:
d.reshape((5,3))

array([[8, 9, 2],
       [2, 8, 9],
       [9, 6, 4],
       [8, 1, 2],
       [6, 7, 5]])

In [58]:
# 1-dim Array Concatenation

In [59]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [60]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [61]:
z=np.array([7,8,9])

In [62]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
# 2 dim matrix Concatenation

In [64]:
a=np.array([[1,2,3],
            [4,5,6]])


In [65]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [66]:
np.concatenate([a,a],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [67]:
np.concatenate([a,a],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [68]:
#Array Splitting(1-dimension)

In [69]:
x=np.array([1,2,3,99,99,3,2,1])

In [70]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [71]:
a,b,c=np.split(x,[3,5])

In [72]:
a

array([1, 2, 3])

In [73]:
b

array([99, 99])

In [74]:
c

array([3, 2, 1])

In [75]:
#Matrix splitting(2 dimension)

In [76]:
m=np.arange(16).reshape(4,4)

In [77]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [78]:
np.vsplit(m,[2]) #vsplit==>vertical split

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [79]:
np.vsplit(m,[3])

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [80]:
up,down=np.vsplit(m,[3])

In [81]:
up

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [82]:
down

array([[12, 13, 14, 15]])

In [83]:
np.hsplit(m,[1])#hsplit==>horizontal split

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11],
        [13, 14, 15]])]

In [84]:
left,right=np.hsplit(m,[1])

In [85]:
left

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [86]:
right

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [87]:
#Array sorting

In [88]:
v=np.array([2,1,4,3,6,5,7])

In [89]:
v

array([2, 1, 4, 3, 6, 5, 7])

In [90]:
np.sort(v)

array([1, 2, 3, 4, 5, 6, 7])

In [91]:
v

array([2, 1, 4, 3, 6, 5, 7])

In [93]:
v.sort()

In [94]:
v

array([1, 2, 3, 4, 5, 6, 7])

In [95]:
# matrix (2 dim ) sorting

In [98]:
m=np.random.randint(1,45,(5,5))

In [99]:
m

array([[30, 42, 11, 23, 23],
       [ 8, 42, 24, 35, 10],
       [32, 30, 27, 11, 21],
       [ 3, 14,  1, 33,  6],
       [14, 16, 15, 32,  9]])

In [102]:
np.sort(m)

array([[11, 23, 23, 30, 42],
       [ 8, 10, 24, 35, 42],
       [11, 21, 27, 30, 32],
       [ 1,  3,  6, 14, 33],
       [ 9, 14, 15, 16, 32]])

In [105]:
np.sort(m,axis=1)

array([[11, 23, 23, 30, 42],
       [ 8, 10, 24, 35, 42],
       [11, 21, 27, 30, 32],
       [ 1,  3,  6, 14, 33],
       [ 9, 14, 15, 16, 32]])

In [106]:
np.sort(m,axis=0)

array([[ 3, 14,  1, 11,  6],
       [ 8, 16, 11, 23,  9],
       [14, 30, 15, 32, 10],
       [30, 42, 24, 33, 21],
       [32, 42, 27, 35, 23]])

In [107]:
#Array index

In [108]:
a= np.random.randint(0,10,size=10)
a

array([0, 0, 9, 3, 0, 9, 1, 1, 6, 4])

In [109]:
a[0]

0

In [110]:
a[-1]

4

In [111]:
a[0]=100

In [112]:
a

array([100,   0,   9,   3,   0,   9,   1,   1,   6,   4])

In [113]:
m= np.random.randint(0,10,size=(3,5))

In [114]:
m

array([[1, 8, 2, 9, 4],
       [3, 7, 4, 6, 3],
       [4, 6, 4, 8, 3]])

In [115]:
m[0,0]

1

In [116]:
m[2,2]

4

In [117]:
m[1,4]=99

In [118]:
m

array([[ 1,  8,  2,  9,  4],
       [ 3,  7,  4,  6, 99],
       [ 4,  6,  4,  8,  3]])

In [119]:
#Getting  a subset of an array by slicing

In [120]:
a=np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [122]:
a[0:3]

array([20, 21, 22])

In [123]:
a[:4]

array([20, 21, 22, 23])

In [124]:
a[5:]

array([25, 26, 27, 28, 29])

In [125]:
a[1::2]

array([21, 23, 25, 27, 29])

In [126]:
a[1::3]

array([21, 24, 27])

In [127]:
#Getting subset of a matrix by slicing

In [128]:
m=np.random.randint(10,size=(5,5))
m

array([[9, 8, 8, 8, 1],
       [3, 3, 5, 0, 0],
       [1, 7, 4, 5, 7],
       [6, 7, 6, 3, 0],
       [6, 0, 0, 1, 2]])

In [129]:
m[3]

array([6, 7, 6, 3, 0])

In [131]:
m[3,:]

array([6, 7, 6, 3, 0])

In [132]:
m[:,0]

array([9, 3, 1, 6, 6])

In [133]:
m[:,1]

array([8, 3, 7, 7, 0])

In [134]:
m

array([[9, 8, 8, 8, 1],
       [3, 3, 5, 0, 0],
       [1, 7, 4, 5, 7],
       [6, 7, 6, 3, 0],
       [6, 0, 0, 1, 2]])

In [135]:
m[0:2,2:]

array([[8, 8, 1],
       [5, 0, 0]])

In [136]:
m[:,0:2]

array([[9, 8],
       [3, 3],
       [1, 7],
       [6, 7],
       [6, 0]])

In [137]:
m[1:3,0:2]

array([[3, 3],
       [1, 7]])

In [1]:
#Operating on a subset of an matrix

In [3]:
import numpy as np
a=np.random.randint(10,size=(5,5))
a

array([[4, 1, 3, 9, 9],
       [8, 4, 7, 4, 5],
       [3, 9, 2, 2, 3],
       [9, 9, 0, 7, 3],
       [5, 1, 8, 3, 6]])

In [5]:
subset_a=a[0:3,0:2]
subset_a

array([[4, 1],
       [8, 4],
       [3, 9]])

In [10]:
subset_a[1,1]=9999

In [11]:
a

array([[   4,    1,    3,    9,    9],
       [   8, 9999,    7,    4,    5],
       [   3,    9,    2,    2,    3],
       [   9,    9,    0,    7,    3],
       [   5,    1,    8,    3,    6]])

In [12]:
m=np.random.randint(10,size=(5,5))
m

array([[6, 1, 5, 4, 0],
       [3, 1, 3, 3, 9],
       [4, 0, 2, 6, 2],
       [3, 8, 5, 0, 2],
       [4, 0, 4, 1, 1]])

In [13]:
subset_b=m[0:3,0:2].copy()
subset_b

array([[6, 1],
       [3, 1],
       [4, 0]])

In [14]:
subset_b[1,1]=88888
subset_b

array([[    6,     1],
       [    3, 88888],
       [    4,     0]])

In [15]:
m

array([[6, 1, 5, 4, 0],
       [3, 1, 3, 3, 9],
       [4, 0, 2, 6, 2],
       [3, 8, 5, 0, 2],
       [4, 0, 4, 1, 1]])

In [16]:
# ACCESSING ITEMS WITH FANCY INDEX

In [17]:
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [18]:
v[1]

3

In [19]:
v[3]

9

In [20]:
v[5]

15

In [21]:
[v[1],v[3],v[5]]

[3, 9, 15]

In [22]:
a=[1,3,5]
v[a]

array([ 3,  9, 15])

In [23]:
v[[1,3,5]]

array([ 3,  9, 15])

In [24]:
# 2-dim fancy index

In [25]:
m=np.arange(9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
m[[0,1],[1,2]]

array([1, 5])

In [27]:
m[[0,2],[0,2]]

array([0, 8])

In [28]:
m[:,[0,2]]

array([[0, 2],
       [3, 5],
       [6, 8]])

In [29]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
m[0,[1,2]]

array([1, 2])

In [32]:
m[1,[0,2]]

array([3, 5])

In [33]:
# fancy with slice indexing

In [35]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [36]:
m[0:,[0,1,2]]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
m[0:,[0,2]]

array([[0, 2],
       [3, 5],
       [6, 8]])

In [38]:
# Conditional operation

In [39]:
v=np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [40]:
v<3

array([ True,  True, False, False, False])

In [41]:
v>2

array([False, False,  True,  True,  True])

In [42]:
v[v>3]

array([4, 5])

In [43]:
v[v<3]

array([1, 2])

In [44]:
v[v >=3 ]

array([3, 4, 5])

In [45]:
v[v!=3]

array([1, 2, 4, 5])

In [46]:
v[v>=2]

array([2, 3, 4, 5])

In [47]:
v

array([1, 2, 3, 4, 5])

In [48]:
v*2

array([ 2,  4,  6,  8, 10])

In [49]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [50]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [51]:
#Mathematical operation

In [52]:
v=np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [53]:
v-1

array([0, 1, 2, 3, 4])

In [55]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [56]:
v*5

array([ 5, 10, 15, 20, 25])

In [58]:
np.subtract(v,3)

array([-2, -1,  0,  1,  2])

In [59]:
np.add(v,3)

array([4, 5, 6, 7, 8])

In [60]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [61]:
np.divide(v,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [62]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [63]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [64]:
v%2

array([1, 0, 1, 0, 1], dtype=int32)

In [65]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [67]:
c=np.array([[4, 0, 3, 0, 1],
       [9, 6, 1, 5, 9],
       [1, 9, 0, 8, 2]])
c

array([[4, 0, 3, 0, 1],
       [9, 6, 1, 5, 9],
       [1, 9, 0, 8, 2]])

In [68]:
c[0:1]

array([[4, 0, 3, 0, 1]])

In [69]:
c[1:3]

array([[9, 6, 1, 5, 9],
       [1, 9, 0, 8, 2]])