In [13]:
import numpy as np
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[[7,8],[9,10]],[[7,8],[9,10]]])

In [15]:
print(x)

[[1 2 3]
 [4 5 6]]


In [16]:
print(y)

[[[ 7  8]
  [ 9 10]]

 [[ 7  8]
  [ 9 10]]]


In [19]:
print(type(x))
print(type(y))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [21]:
print(x.shape) #the number of rows and columns
print(y.shape)#==>> 2 kere 2X2 boyutunda matris olarak dusunebilirsin

(2, 3)
(2, 2, 2)


In [23]:
print(x.size) # number of records or entity
print(y.size)

6
8


In [24]:
print(x.ndim) # dimension of array 
print(y.ndim) 

2
3


In [25]:
print(x.dtype)
print(y.dtype)

int64
int64


In [26]:
print(x.nbytes)
print(y.nbytes)

48
64


# 2

In [30]:
x1=np.array([1,2,3],   dtype=np.int)
x2=np.array([1.3,4.6,7.6],  dtype=np.float)
print(x1+x2)
print((x1+x2).dtype)

[ 2.3  6.6 10.6]
float64


In [31]:
a=np.sqrt(np.array([-1,9,4],dtype=np.float))
print(a)
print(a.dtype)

[nan  3.  2.]
float64


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


In [32]:
b=np.sqrt(np.array([-1,9,4],dtype=np.complex))
print(b)
print(b.dtype)


[0.+1.j 3.+0.j 2.+0.j]
complex128


In [34]:
print(b.real)
print(b.imag)
print((b.real).dtype)
print((b.imag).dtype)

[0. 3. 2.]
[1. 0. 0.]
float64
float64


# 3

In [4]:
import numpy as np
x1=np.zeros(4)
x1

array([0., 0., 0., 0.])

In [6]:
y1=np.ones(4)
y1

array([1., 1., 1., 1.])

In [8]:
x2=np.zeros((2,3,4),dtype=np.int)
x2# 2 tane (3,4)  matrixden olusuyor(3 boyutlu)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [9]:
y2=np.ones((4,6))
y2

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [10]:
x3=np.full((3,4),10, dtype=np.float) #3 satir ve 4 sutundan  ve icerisnde sadece sabit  10 degeri olan bir matrix olusturur
x3

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [14]:
y3=10.0 * np.ones((2,3))
z3=10.0 + np.zeros((2,3))
print(y3)
print(z3)

[[10. 10. 10.]
 [10. 10. 10.]]
[[10. 10. 10.]
 [10. 10. 10.]]


In [15]:
a=np.empty((3,3))
a

array([[1.4663133e-316, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [16]:
a.fill(3)# bos olan a array in 3 ile doldurdu
a

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [20]:
b=np.eye(4)# birim matrix oluturur  kosegeni 1 olan elemanlardan olusur
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
a1=np.eye(6)
a2=np.eye(6, k=1)
a3=np.eye(6, k=-2)
print(a1)
print("************************")
print(a2)
print("*************************")
print(a3)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
************************
[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]
*************************
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


In [24]:
np.identity(5)# birim matrix olusturur

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.diag([4,6,8,6,11])# verilen listedeki elemanlari   dioganala yerlestirir

array([[ 4,  0,  0,  0,  0],
       [ 0,  6,  0,  0,  0],
       [ 0,  0,  8,  0,  0],
       [ 0,  0,  0,  6,  0],
       [ 0,  0,  0,  0, 11]])

# 4

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(4,10)# 4 ten baslayip 10 akadar  10 dahil degil

array([4, 5, 6, 7, 8, 9])

In [29]:
np.arange(3,23,4)# 3 ten 23(23 dahil degil) ye kadar 4 artarak  array olusturu

array([ 3,  7, 11, 15, 19])

In [30]:
np.linspace(0,15,5)# 0 dan 15 e kadar(15 dahil) arasinda 5 tane sayi olusturacak sekilde array olusturur

array([ 0.  ,  3.75,  7.5 , 11.25, 15.  ])

In [32]:
np.linspace(0,30,10)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        , 23.33333333, 26.66666667, 30.        ])

In [34]:
np.linspace(0,15,8, endpoint=False)# bitis dgerini almaz. yani 15 dahil degil

array([ 0.   ,  1.875,  3.75 ,  5.625,  7.5  ,  9.375, 11.25 , 13.125])

In [36]:
x4=np.arange(20)
x4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [37]:
np.reshape(x4,(4,5))# tek boyulu arrayi 4satir 5 sutunlu bi matrixe cevirdi

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [38]:
x5=np.arange(32)
x5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [39]:
np.reshape(x5,(2,4,4))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [40]:
x6=np.linspace(0,19,20)
x6

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [41]:
np.reshape(x6,(2,10))

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.]])

In [42]:
np.linspace(0,19,20).reshape(2,10)# yukaridaki iki islemin  birlikte yapilmis hali

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.]])

In [45]:
np.random.random((2,3))# 0 ile 1(1 dahil degil) arasindan  ondalikli  rasgele degerler secerek  2X3 luk  matrix olusturur

array([[0.9899113 , 0.22150105, 0.27984848],
       [0.02466737, 0.47150736, 0.04635458]])

In [47]:
np.random.randint(3,12,size=(4,5)) # 3 ile 12 arasinda(12 dahil degil) rasgele tamsayilar secerek 4X5 lik matrix oluturur

array([[ 5,  5,  6,  8,  5],
       [ 5, 11,  7, 10,  4],
       [10,  9,  5,  6, 10],
       [ 4,  8,  6,  8,  7]])

# 5

In [1]:
import numpy as np
x=np.arange(5)
x

array([0, 1, 2, 3, 4])

In [4]:
x[0]

0

In [5]:
x[2]

2

In [6]:
x[-2]

3

In [12]:
x[-1]

4

In [13]:
x[-5]

0

In [14]:
x[2]=200
x

array([  0,   1, 200,   3,   4])

In [15]:
x1=np.arange(12).reshape(3,4)
x1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
x1[0]

array([0, 1, 2, 3])

In [17]:
x1[1]

array([4, 5, 6, 7])

In [19]:
x1[0,0]

0

In [20]:
x1[2,3]

11

In [21]:
x1[2,2] # x1[rowindex, columnindex]

10

In [23]:
x1[0,0]=100
x1

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

#### delete function

In [26]:
x2=np.arange(6)
print(x2)
y=np.delete(x2,[0,1])# x2 arrayindeki elemanlari al ve 0 ve 1 inddexlerdeki elemanlari sil ve kalan degereleri y array olarak ata.
print(y)

[0 1 2 3 4 5]
[2 3 4 5]


In [28]:
x3=np.arange(16).reshape(4,4)
print(x3)
print("============================")
y1=np.delete(x3,1, axis=0)# x3 arrayindeki  row bazinda 1.indexdeki satiri sil ve kalan sutun ve satirlari y1 ata
print(y1)
                           #axis=0 ====>> row bazinda isle yapar
                            #axis=1 ====>> column bazinda islem yapar 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]


In [35]:
x3=np.arange(16).reshape(4,4)
print(x3)
print("============================")
y2=np.delete(x3,[0,2], axis=1)# x3 arrayindeki  column bazinda 0. ve 2. indexdeki sutunlari sil ve kalan sutun ve satirlari y2 ata
print(y2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


#### append function

In [37]:
x4=np.arange(5)
print(x4)
print("============================")
y3=np.append(x4,100)
print(y3)

[0 1 2 3 4]
[  0   1   2   3   4 100]


In [38]:
x4=np.arange(5)
print(x4)
print("============================")
y4=np.append(x4,[200,300])
print(y4)

[0 1 2 3 4]
[  0   1   2   3   4 200 300]


In [49]:
x5=np.arange(9).reshape(3,3)
print(x5)
print("============================")
y6=np.append(x5,[[100,200,300]],axis=0)
print(y6)
print("============================")
y7=np.append(y6,[[100],[200],[300],[400]],axis=1)#  herbir elemani koseli parantez icine alip ekledik
print(y7)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[  0   1   2]
 [  3   4   5]
 [  6   7   8]
 [100 200 300]]
[[  0   1   2 100]
 [  3   4   5 200]
 [  6   7   8 300]
 [100 200 300 400]]


#### insert function

In [ ]:
#np.insert(array,index,element,axis)

In [52]:
x6= np.arange(5)
print(x6)
print("============================")
y8=np.insert(x6,3,250)#3. indexe 250 sayisini yerlestirdik
print(y8)
print("============================")
y9=np.insert(x6,2,[460,710])# 2. indexe 460 ve 710 degerlerini arka arkaya sirasyla yerlestirdi
print(y9)

[0 1 2 3 4]
[  0   1   2 250   3   4]
[  0   1 460 710   2   3   4]


In [57]:
x7=np.arange(9).reshape(3,3)
print(x7)
print("============================")
y10=np.insert(x7,1,[100,200,300],axis=0)# x7 arrayine satir bazinda 1 indexteki degerler [100,200,300] olacak sekilde ekledi ve bunu y10 arrayine atadi
print(y10)
print("============================")
y11=np.insert(y10,1,[15,25,35,45],axis=1)
print(y11)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[  0   1   2]
 [100 200 300]
 [  3   4   5]
 [  6   7   8]]
[[  0  15   1   2]
 [100  25 200 300]
 [  3  35   4   5]
 [  6  45   7   8]]


#### stack function

In [69]:
x=np.arange(3)
print(x)
print("============================")
y=np.arange(9).reshape(3,3)
print(y)
print("============================")
z=np.vstack((x,y))# xi ye dikey olarak ekler.burada satir sayisi artacak. vstack==> verticalstack==> dikey bilestirme
print(z)
print("============================")
t=np.hstack((x,y.reshape(9,)))


[0 1 2]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [0 1 2]
 [3 4 5]
 [6 7 8]]


# 6

In [2]:
import numpy as np

# 1d array slicing

In [3]:
# ndarray[start:end], ndarray[start:] , ndarray[:end]

In [4]:
x=np.arange(10)
print(x)
print("=================")
print(x[2:6])# 2. index dahil, 6 index dahil ddegil
print("=================")
print(x[2:])
print("=================")
print(x[:7])


[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5]
[2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6]


In [5]:
print("=================")
print(x[:-1])
print("=================")
print(x[-1:])
print("=================")
print(x[-4:-2])

[0 1 2 3 4 5 6 7 8]
[9]
[6 7]


# 2d array slicing

In [6]:
# 2darray[satir araliklari  , sutun araliklari]

In [9]:
x1= np.arange(25).reshape(5,5)
print(x1)
print("========================")
print(x1[0:3,1:4])
print("========================")
print(x1[2:])
print("========================")
print(x1[::])
print("========================")
print(x1[:,3:])





[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]]


# 7

In [10]:
import numpy as np

In [13]:
x=np.linspace(1,21,11)
print(x)
print("======================")
y=np.array([2,4,7])
print(y)
print("======================")
print(x[y])

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21.]
[2 4 7]
[ 5.  9. 15.]


In [19]:
x1=np.arange(25).reshape(5,5)
print(x1)
print("======================")
y1=np.array([1,2])
print(y1)
print("======================")
print(x1[y1,:])
print("======================")
print(x1[:,y1])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[1 2]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]]


### boolean indexing

In [34]:
x2=np.arange(10)
print(x2)
print("======================")
print(x2[x2%2==0])
print("======================")
print(x2[x2>5])
print("======================")
print(x2[(x2>3) & (x2<8)])   # &  ISARET AND ANLAMAINA GELIR
print("======================")
print(x2[(x2<2) | (x2>8)])   #  | isaret OR anlamina gelir


[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[6 7 8 9]
[4 5 6 7]
[0 1 9]


# 8 

In [1]:
import numpy as np
x=np.array([2,3,5,6,9])
y=np.array([6,1,7,8,3])

In [2]:
np.intersect1d(x,y)#  kesisim elemanlarini getirir

array([3, 6])

In [3]:
np.setdiff1d(x,y)# x de olan y de olmayan elemanlari   kume formatinda yaniher lemam bir adet olacak sekilde getirir

array([2, 5, 9])

In [4]:
np.setdiff1d(y,x)# y de olup x de olmayanlari getirir

array([1, 7, 8])

In [5]:
np.union1d(x,y)# iki arrayi bilestirere yanliz ortak olan elemamlari birkez yazacak 

array([1, 2, 3, 5, 6, 7, 8, 9])

In [6]:
np.in1d(x,y)# x de  buluna n lemanlar  ye de varsa sirasiyla kontrol eder ve true veya false yazdirir

array([False,  True, False,  True, False])

##### sort

In [8]:
x1=np.random.randint(1,10,size=(10,))
x1

array([4, 2, 5, 6, 3, 2, 7, 7, 3, 2])

In [11]:
print(np.sort(x1))# fonksiyon seklindeki sort bir degisken atanmazaza arrayin orjinal halinde herhangi bi dgeisklik 
print(x1)

[2 2 2 3 3 4 5 6 7 7]
[4 2 5 6 3 2 7 7 3 2]


In [19]:
y1=np.random.randint(1,10,size=(10,))
y1

array([5, 8, 1, 5, 2, 8, 4, 5, 5, 4])

In [20]:
y1.sort()# method olarak kullanirsak direk  array siraliyor . orjinal array uzerinde degisiklik yapmi oldu


In [21]:
y1

array([1, 2, 4, 4, 5, 5, 5, 5, 8, 8])

### 2d array sort

In [22]:
x3=np.random.randint(1,10, size=(5,5))
x3

array([[2, 4, 6, 2, 3],
       [6, 4, 5, 8, 7],
       [9, 8, 1, 5, 2],
       [9, 3, 1, 5, 5],
       [7, 5, 7, 6, 4]])

In [23]:
np.sort(x3, axis=0)# axis=0  sutunlar gore siralr. ama degisiklik kalici degil

array([[2, 3, 1, 2, 2],
       [6, 4, 1, 5, 3],
       [7, 4, 5, 5, 4],
       [9, 5, 6, 6, 5],
       [9, 8, 7, 8, 7]])

In [24]:
x3

array([[2, 4, 6, 2, 3],
       [6, 4, 5, 8, 7],
       [9, 8, 1, 5, 2],
       [9, 3, 1, 5, 5],
       [7, 5, 7, 6, 4]])

In [25]:
np.sort(x3, axis=1)# axis=1  satirlara gore siralar. ama degisiklik kalici degil

array([[2, 2, 3, 4, 6],
       [4, 5, 6, 7, 8],
       [1, 2, 5, 8, 9],
       [1, 3, 5, 5, 9],
       [4, 5, 6, 7, 7]])

# 9

In [28]:
import numpy as np
x=np.random. randint(1,10,size=(3,3))
print(x)
print("==========================")
print(np.sqrt(x))
print("==========================")
print(np.power(x,3))
print("==========================")
print(np.exp(x))
print("==========================")
print(np.sum(x))

[[3 7 4]
 [3 4 3]
 [9 2 6]]
[[1.73205081 2.64575131 2.        ]
 [1.73205081 2.         1.73205081]
 [3.         1.41421356 2.44948974]]
[[ 27 343  64]
 [ 27  64  27]
 [729   8 216]]
[[2.00855369e+01 1.09663316e+03 5.45981500e+01]
 [2.00855369e+01 5.45981500e+01 2.00855369e+01]
 [8.10308393e+03 7.38905610e+00 4.03428793e+02]]
41


# 10 

In [5]:
import numpy as np
x=np.random.randint(1,10, size=(8,))
print(x)
print("==========================")
print(x.mean())
print("==========================")
print(np.median(x))
print("==========================")
print(x.std())

[9 9 1 2 5 6 5 9]
5.75
5.5
2.947456530637899


In [9]:
y=np.random.randint(1,10, size=(4,3))
print(y)
print("==========================")
print(y.mean(axis=0))#axis=0 sutunlarin aritmetik ortalamasini verir
print("==========================")
print(np.median(y,axis=1))# axis=1 satirlarin medyan degerin verir
print("==========================")
print(y.std(axis=0))

[[4 2 7]
 [5 1 7]
 [1 5 7]
 [2 7 4]]
[3.   3.75 6.25]
[4. 5. 5. 4.]
[1.58113883 2.384848   1.29903811]


In [10]:
a=np.random.randint(1,10, size=(3,2))
b=np.random.randint(1,10, size=(3,2))
print(a)
print("==========================")
print(b)
print("==========================")
print(a+b)
print("==========================")

[[6 4]
 [9 8]
 [9 5]]
[[9 4]
 [9 3]
 [7 8]]
[[15  8]
 [18 11]
 [16 13]]


#### Broadcasting

In [15]:
a1=np.random.randint(1,10, size=(1,))
b1=np.random.randint(1,10, size=(3,2))
print(a1)
print("==========================")
print(b1)
print("==========================")
print(a1+b1)
print("==========================")

[9]
[[7 3]
 [9 8]
 [2 7]]
[[16 12]
 [18 17]
 [11 16]]


In [16]:
a2=np.random.randint(1,10, size=(2,))
b2=np.random.randint(1,10, size=(3,2))
print(a2)
print("==========================")
print(b2)
print("==========================")
print(a2+b2)
print("==========================")

[9 2]
[[2 3]
 [5 7]
 [6 7]]
[[11  5]
 [14  9]
 [15  9]]


In [17]:
a2=np.random.randint(1,10, size=(3,1))
b2=np.random.randint(1,10, size=(1,3))
print(a2)
print("==========================")
print(b2)
print("==========================")
print(a2+b2)
print("==========================")

[[5]
 [4]
 [6]]
[[2 1 7]]
[[ 7  6 12]
 [ 6  5 11]
 [ 8  7 13]]


# 11

In [18]:
import numpy as np

In [21]:
x=np.zeros((5,3))
y=np.ones(5)
print(x)
print("==========================")
print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]


In [22]:
np.arange(7,42,2)

array([ 7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39,
       41])

In [25]:
np.random.randint(1,10,size=(4,4))

array([[4, 8, 9, 5],
       [9, 1, 6, 7],
       [8, 3, 2, 6],
       [2, 4, 9, 2]])

In [26]:
np.linspace(0.1,1,10)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [29]:
x=np.arange(25).reshape(5,5)
x[1:3,2:4]

array([[ 7,  8],
       [12, 13]])

In [ ]:
np.arange(1,17)